### ISSUE TITLE
Why is ReceivedMessage object null 

### ISSUE THREAD

**Issue by HypertinIsBehindYou** [isdaviddong/chatGPTLineBot#1]
I am wondering why my receivemessage object is null, which causing object reference not set to an instance of an object error. I did receive the line 24 "Try getting receivedmessage..." message thru line channel but couldn't get any further. 

![Snag_461a5d97](https://user-images.githubusercontent.com/7965465/205812035-7898b8fa-74ab-43ed-a57e-8e21e391b019.png)

Thank you for you assistance!

**Comment by isdaviddong** [comment]
ReceivedMessage is the SDK directly converts from the received JSON message back through deserialization, so it should not be null. I am not sure under what circumstances you received null value. It may be caused by the Verify button of LINE console. 

It is recommended to first modify your code to exclude null .
